
package com.realdolmen.brentvw.bookstore.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "BookOrderServiceService", targetNamespace = "http://service.realdolmen.com/", wsdlLocation = "file:/mnt/c/Users/BVWBL01/Documents/bla/orderbook.wsdl")
public class BookOrderServiceService
    extends Service
{

    private final static URL BOOKORDERSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException BOOKORDERSERVICESERVICE_EXCEPTION;
    private final static QName BOOKORDERSERVICESERVICE_QNAME = new QName("http://service.realdolmen.com/", "BookOrderServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/mnt/c/Users/BVWBL01/Documents/bla/orderbook.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BOOKORDERSERVICESERVICE_WSDL_LOCATION = url;
        BOOKORDERSERVICESERVICE_EXCEPTION = e;
    }

    public BookOrderServiceService() {
        super(__getWsdlLocation(), BOOKORDERSERVICESERVICE_QNAME);
    }

    public BookOrderServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), BOOKORDERSERVICESERVICE_QNAME, features);
    }

    public BookOrderServiceService(URL wsdlLocation) {
        super(wsdlLocation, BOOKORDERSERVICESERVICE_QNAME);
    }

    public BookOrderServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BOOKORDERSERVICESERVICE_QNAME, features);
    }

    public BookOrderServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BookOrderServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BookOrderService
     */
    @WebEndpoint(name = "BookOrderServicePort")
    public BookOrderService getBookOrderServicePort() {
        return super.getPort(new QName("http://service.realdolmen.com/", "BookOrderServicePort"), BookOrderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BookOrderService
     */
    @WebEndpoint(name = "BookOrderServicePort")
    public BookOrderService getBookOrderServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.realdolmen.com/", "BookOrderServicePort"), BookOrderService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BOOKORDERSERVICESERVICE_EXCEPTION!= null) {
            throw BOOKORDERSERVICESERVICE_EXCEPTION;
        }
        return BOOKORDERSERVICESERVICE_WSDL_LOCATION;
    }

}
