
package com.realdolmen.brentvw.bookstore.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookOrderService", targetNamespace = "http://service.realdolmen.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookOrderService {


    /**
     * 
     * @param bookId
     * @return
     *     returns com.realdolmen.service.Order
     */
    @WebMethod
    @WebResult(name = "order", targetNamespace = "")
    @RequestWrapper(localName = "orderBook", targetNamespace = "http://service.realdolmen.com/", className = "com.realdolmen.brentvw.bookstore.service.OrderBook")
    @ResponseWrapper(localName = "orderBookResponse", targetNamespace = "http://service.realdolmen.com/", className = "com.realdolmen.brentvw.bookstore.service.OrderBookResponse")
    public Order orderBook(
            @WebParam(name = "bookId", targetNamespace = "")
                    int bookId);

}
